# Base image
FROM node:24-alpine AS builder

WORKDIR /app

# Copy root files
COPY package*.json ./
COPY turbo.json ./

RUN npm install

# Copy repo
COPY . .

# Build apps
RUN npx turbo run build

# Production stage
FROM node:24-alpine AS runner

WORKDIR /app

COPY --from=base /app .

ENV NODE_ENV=production

# NestJS port
EXPOSE 3000

CMD ["node", "apps/server/dist/main.js"]