version: "5.1.0"

services:
  api:
    container_name: doctor-api
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./apps/server/.env.prod
    restart: always