# ---------- BUILD STAGE ----------
FROM node:24-alpine AS builder

WORKDIR /app

# copy root files first for caching
COPY package*.json turbo.json ./

RUN npm install

# copy repo
COPY . .

# build monorepo
RUN npx turbo run build


# ---------- RUNTIME STAGE ----------
FROM node:24-alpine AS runner

WORKDIR /app

# copy built app
COPY --from=builder /app .

EXPOSE 3000

CMD ["node", "apps/server/dist/main.js"]