import { BASE_SPECIALIZATION_ENDPOINT } from "@endpoints/specialization-endpoint";

const SpecializationActionTypes = {
  SPECIALIZATION_GET_ALL: `${BASE_SPECIALIZATION_ENDPOINT}`,
  SPECIALIZATION_GET_BY_ID: `${BASE_SPECIALIZATION_ENDPOINT}/get-by-id`,
  SPECIALIZATION_CREATE: `${BASE_SPECIALIZATION_ENDPOINT}/create`,
  SPECIALIZATION_UPDATE: `${BASE_SPECIALIZATION_ENDPOINT}/update`,
  SPECIALIZATION_DELETE: `${BASE_SPECIALIZATION_ENDPOINT}/delete`,
};

export { SpecializationActionTypes };
